### PR TITLE
Updated RDPEI API const correctness, added stubs for new functions

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Review by hardening — COMMENTED** [review]
This PR is nice, but perhaps we should also cast force when assigning callbacks so that it would also work with early FreeRDP 2.2 .

**Comment by hardening** [comment]
Another possibility is testing the version number and playing with `ifdef` (yeah not the best choice), but we will kinda need it as the Pen callbacks aren't there in early versions.

**Comment by akallabeth** [comment]
@hardening any specific reason you need to support 2.2?
As for casting, don´t like it as it hides problems. Should only be used if there is a very specific reason and for callbacks that is most likely never a good idea.
Reason I´m asking is because any system using `FreeRDP 2.2` will not have ogon anyway

**Comment by hardening** [comment]
I don't like either the forced casts.
I don't have any other reason than compatibility with both `FreeRDP-ogon` and `FreeRDP 2.2`. Another scenario is systems that have FreeRDP 2.2 installed system wide.

**Comment by akallabeth** [comment]
@hardening ok, did check and added version defines for the compatibility stuff.

**Comment by hardening** [comment]
May I suggest to define a `OLD_FREERP_TOUCH_API` depending on the version, so that we have version checks in just one place ?

**Comment by akallabeth** [comment]
@hardening done

**Review by hardening — APPROVED** [review]
I don't see why `USE_OLD_FREERDP_TOUCH_API` should be a function, but that does the job, approuved.

**Comment by hardening** [comment]
An now we're waiting for @bmiklautz to merge it !

**Pull request merged**
